require_relative 'classes/item'
require_relative 'classes/game'
require_relative 'classes/author'
require_relative 'classes/music'
require_relative 'classes/genre'
require_relative 'classes/movie'
require_relative 'classes/source'
require_relative 'validation'
require_relative 'handler/handle_label'
require_relative 'handler/handle_genre'
require_relative 'handler/handle_author'

require 'json'
